AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stitch SVG to PES Converter - Complete Infrastructure'

# Global Tags

Metadata:
  Tags:
    - Key: brand
      Value: urgd
    - Key: project
      Value: stitch

Parameters:
  Environment:
    Type: String
    Default: 'prod'
    Description: 'Environment name (prod, dev, staging)'
    AllowedValues: ['prod', 'dev', 'staging']
  
  DomainName:
    Type: String
    Default: 'urgdstudios.com'
    Description: 'Base domain name for the service'
  
  Subdomain:
    Type: String
    Default: 'stitch'
    Description: 'Subdomain for the service (e.g., stitch.urgdstudios.com)'
  
  CertificateArn:
    Type: String
    Description: 'ARN of the SSL certificate for the domain (must be in us-east-1)'
    Default: 'arn:aws:acm:us-east-1:198919428218:certificate/90d330b3-ad6c-4b24-9a9e-9188ededc595'
  
  HostedZoneId:
    Type: String
    Default: 'Z0338626TGE7PTZDLIT1'
    Description: 'Route 53 Hosted Zone ID for the domain'
  
  ArtifactsBucketName:
    Type: String
    Description: 'Name of the existing S3 bucket for Lambda code and layers'
    Default: 'urgd-applicationdata'

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]

Resources:
  # S3 Bucket for user temporary file storage
  StitchStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'urgd-stitch-storage-${Environment}-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Id: DeleteTempFiles
            Status: Enabled
            ExpirationInDays: 1
            Prefix: 'temp/'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: brand
          Value: urgd
        - Key: project
          Value: stitch

  # IAM Role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'urgd-stitch-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${StitchStorageBucket}/*'
      Tags:
        - Key: brand
          Value: urgd
        - Key: project
          Value: stitch

  # Lambda Layer for dependencies
  StitchLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub 'urgd-stitch-libs-${Environment}'
      Description: 'Dependencies for Stitch SVG to PES converter'
      Content:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: 'stitch/layers/stitch-libs.zip'
      CompatibleRuntimes:
        - python3.11

  # Lambda Function
  StitchFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'urgd-stitch-${Environment}'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: 'stitch/lambda/stitch-function.zip'
      MemorySize: 512
      Timeout: 30
      Layers:
        - !Ref StitchLayer
      Environment:
        Variables:
          BUCKET_NAME: !Ref StitchStorageBucket
      Tags:
        - Key: brand
          Value: urgd
        - Key: project
          Value: stitch

  # S3 Bucket for static website hosting
  StitchWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'urgd-stitch-website-${Environment}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: brand
          Value: urgd
        - Key: project
          Value: stitch

  # S3 Bucket Policy for public read access
  StitchWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StitchWebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${StitchWebsiteBucket}/*'

  # API Gateway REST API for Lambda function
  StitchApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'urgd-stitch-api-${Environment}'
      Description: 'API Gateway for Stitch SVG to PES converter API'
      EndpointConfiguration:
        Types:
          - REGIONAL
      BinaryMediaTypes:
        - '*/*'
      Tags:
        - Key: brand
          Value: urgd
        - Key: project
          Value: stitch

  # API Gateway Lambda Permission
  StitchApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StitchFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${StitchApiGateway}/*/*'

  # API Gateway Resource for /api path
  StitchApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref StitchApiGateway
      ParentId: !GetAtt StitchApiGateway.RootResourceId
      PathPart: api

  # API Gateway Method for POST requests (file conversion)
  StitchApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StitchApiGateway
      ResourceId: !Ref StitchApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StitchFunction.Arn}/invocations'

  # API Gateway Method for OPTIONS requests (CORS)
  StitchApiGatewayOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StitchApiGateway
      ResourceId: !Ref StitchApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true

  # API Gateway Deployment
  StitchApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - StitchApiGatewayMethod
      - StitchApiGatewayOptionsMethod
    Properties:
      RestApiId: !Ref StitchApiGateway
      StageName: !Ref Environment

  # API Gateway Custom Domain
  StitchApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Condition: HasCertificate
    Properties:
      DomainName: !Sub 'api.${Subdomain}.urgd.dev'
      CertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: brand
          Value: urgd
        - Key: project
          Value: stitch

  # API Gateway Base Path Mapping
  StitchApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: HasCertificate
    Properties:
      DomainName: !Ref StitchApiDomainName
      RestApiId: !Ref StitchApiGateway
      Stage: !Ref StitchApiGatewayDeployment

  # CloudFront Distribution
  StitchCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: HasCertificate
    Properties:
      DistributionConfig:
        Comment: !Sub 'Stitch SVG to PES Converter - ${Subdomain}.${DomainName}'
        Enabled: true
        Aliases:
          - !Sub '${Subdomain}.${DomainName}'
        Origins:
          - Id: StitchWebsiteOrigin
            DomainName: !GetAtt StitchWebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
          - Id: StitchApiOrigin
            DomainName: !Sub 'api.${Subdomain}.urgd.dev'
            CustomOriginConfig:
              HTTPPort: 443
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: StitchWebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CacheBehaviors:
          - PathPattern: '/api/*'
            TargetOriginId: StitchApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - POST
              - PUT
              - DELETE
              - PATCH
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
              Headers:
                - Authorization
                - Content-Type
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
      Tags:
        - Key: brand
          Value: urgd
        - Key: project
          Value: stitch

  # Route 53 Record
  StitchDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasCertificate
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '${Subdomain}.${DomainName}'
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt StitchCloudFrontDistribution.DomainName

  # Route 53 Record for API domain
  StitchApiDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasCertificate
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'api.${Subdomain}.urgd.dev'
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt StitchApiDomainName.DistributionDomainName

Outputs:
  WebsiteUrl:
    Description: 'S3 Website URL'
    Value: !GetAtt StitchWebsiteBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteUrl'
  
  ApiUrl:
    Description: 'API Gateway URL'
    Value: !Sub 'https://${StitchApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'
  
  ApiDomainUrl:
    Description: 'API Custom Domain URL'
    Condition: HasCertificate
    Value: !Sub 'https://api.${Subdomain}.urgd.dev'
    Export:
      Name: !Sub '${AWS::StackName}-ApiDomainUrl'
  
  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Condition: HasCertificate
    Value: !Ref StitchCloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'
  
  CloudFrontUrl:
    Description: 'CloudFront Distribution URL'
    Condition: HasCertificate
    Value: !Sub 'https://${StitchCloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'
  
  CustomDomainUrl:
    Description: 'Custom domain URL'
    Condition: HasCertificate
    Value: !Sub 'https://${Subdomain}.${DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CustomDomainUrl'
  
  S3BucketName:
    Description: 'S3 bucket for temporary file storage'
    Value: !Ref StitchStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'
