name: Build Ultimate 21-Layer Lambda Arsenal

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev/staging/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build-ultimate-layers:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libwebp-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libxcb1-dev \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            libncursesw5-dev \
            xz-utils \
            tk-dev \
            libxml2-dev \
            libxmlsec1-dev \
            libffi-dev \
            liblzma-dev \
            libopenblas-dev \
            liblapack-dev \
            gfortran \
            libhdf5-dev \
            pkg-config \
            cmake \
            libgtk-3-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libv4l-dev \
            libxvidcore-dev \
            libx264-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libatlas-base-dev \
            gfortran \
            wget \
            unzip

      - name: Build All 21 Layers
        run: |
          echo "🔥 Building all 21 individual Lambda layers..."
          
          # List of all layers
          layers=("pillow" "numpy" "opencv" "scipy" "svgpathtools" "svgpath" "pyembroidery" "multipart" "scikit-image" "imageio" "rawpy" "exifread" "pillow-heif" "scikit-learn" "numba" "joblib" "pandas" "matplotlib" "seaborn" "cairosvg" "svglib" "reportlab")
          
          # Build each layer
          for layer in "${layers[@]}"; do
            echo "🔥 Building $layer layer..."
            
            # Create build directory
            mkdir -p ${layer}-build
            cd ${layer}-build
            
            # Copy requirements
            cp ../layers/${layer}/requirements.txt .
            
            # Install Python dependencies
            pip install --upgrade pip setuptools wheel
            echo "⚡ Installing $layer dependencies..."
            pip install -r requirements.txt -t ./python/ --no-cache-dir
            
            # Create the layer zip
            echo "💥 Creating $layer layer package..."
            zip -r ${layer}.zip python/
            
            # Get the size
            LAYER_SIZE=$(du -h ${layer}.zip | cut -f1)
            echo "🎯 ${layer^^} LAYER BUILT! Size: $LAYER_SIZE"
            
            # Upload to S3
            aws s3 cp ${layer}.zip s3://urgd-applicationdata/stitch/layers/${layer}.zip --region us-west-2
            
            echo "🚀 ${layer^^} LAYER DEPLOYED TO S3!"
            
            # Go back to root
            cd ..
          done

      - name: Publish All 21 Layers
        run: |
          echo "🔥 Publishing all 21 Lambda layers..."
          
          # List of all layers
          layers=("pillow" "numpy" "opencv" "scipy" "svgpathtools" "svgpath" "pyembroidery" "multipart" "scikit-image" "imageio" "rawpy" "exifread" "pillow-heif" "scikit-learn" "numba" "joblib" "pandas" "matplotlib" "seaborn" "cairosvg" "svglib" "reportlab")
          
          # Publish each layer
          for layer in "${layers[@]}"; do
            echo "🔥 Publishing $layer layer..."
            
            # Create layer
            LAYER_ARN=$(aws lambda publish-layer-version \
              --layer-name urgd-${layer}-${{ github.event.inputs.environment }} \
              --description "${layer^} - ${{ github.event.inputs.environment }}" \
              --content S3Bucket=urgd-applicationdata,S3Key=stitch/layers/${layer}.zip \
              --compatible-runtimes python3.12 \
              --compatible-architectures x86_64 \
              --query 'LayerVersionArn' \
              --output text \
              --region us-west-2)
            
            echo "🎯 ${layer^} Layer ARN: $LAYER_ARN"
            echo "${layer^^}_LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV
          done

      - name: Output Layer Info
        run: |
          echo "🚀 ALL 21 LAMBDA LAYERS DEPLOYED!"
          echo "💪 The ultimate Python arsenal is ready!"
          echo "🔥 Each package gets its own layer - maximum modularity!"
          echo "⚡ Ready to power your Lambda functions!"
          echo ""
          echo "📝 Layer ARNs:"
          echo "  - $PILLOW_LAYER_ARN"
          echo "  - $NUMPY_LAYER_ARN"
          echo "  - $OPENCV_LAYER_ARN"
          echo "  - $SCIPY_LAYER_ARN"
          echo "  - $SVGPATHTOOLS_LAYER_ARN"
          echo "  - $SVGPATH_LAYER_ARN"
          echo "  - $PYEMBROIDERY_LAYER_ARN"
          echo "  - $MULTIPART_LAYER_ARN"
          echo "  - $SCIKIT_IMAGE_LAYER_ARN"
          echo "  - $IMAGEIO_LAYER_ARN"
          echo "  - $RAWPY_LAYER_ARN"
          echo "  - $EXIFREAD_LAYER_ARN"
          echo "  - $PILLOW_HEIF_LAYER_ARN"
          echo "  - $SCIKIT_LEARN_LAYER_ARN"
          echo "  - $NUMBA_LAYER_ARN"
          echo "  - $JOBLIB_LAYER_ARN"
          echo "  - $PANDAS_LAYER_ARN"
          echo "  - $MATPLOTLIB_LAYER_ARN"
          echo "  - $SEABORN_LAYER_ARN"
          echo "  - $CAIROSVG_LAYER_ARN"
          echo "  - $SVGLIB_LAYER_ARN"
          echo "  - $REPORTLAB_LAYER_ARN"